<?php

return [
    'websites' => [
        'slug' => 'criacao-sites-porto',
        'seo' => [
            'title' => 'Criação de Sites no Porto para Empresas | NexusVora',
            'description' => 'Criação de sites profissionais no Porto para empresas. Websites rápidos, preparados para Google, formulários de contacto e acompanhamento próximo.',
        ],
        'eyebrow' => 'Websites & presença digital',
        'title' => 'Criação de sites no Porto para empresas que querem receber mais contactos.',
        'lead' => 'Um website profissional deve explicar o seu negócio com clareza, transmitir confiança e facilitar o contacto de quem já procura o seu serviço no Google.',
        'intro' => 'Criamos sites profissionais, websites institucionais, landing pages e lojas online para empresas no Porto, Gaia e Maia. Combinamos web design, desenvolvimento web e estrutura para SEO, a partir do cliente que quer atrair e da ação que espera que ele tome.',
        'accent' => 'cyan',
        'features' => [
            ['title' => 'Estratégia antes do web design', 'text' => 'Organizamos mensagem, páginas e chamadas para ação para o cliente perceber rapidamente o valor da empresa.'],
            ['title' => 'Rápido e preparado para Google', 'text' => 'Criamos uma base técnica sólida para telemóvel, velocidade, SEO técnico, indexação e crescimento orgânico.'],
            ['title' => 'Preparado para evoluir', 'text' => 'Incluímos formulários, analytics, integrações e manutenção para o website continuar útil depois do lançamento.'],
        ],
        'for' => ['PMEs sem website ou com um site desatualizado', 'Empresas locais que querem gerar mais contactos', 'Negócios que precisam de uma base para SEO, Ads ou e-commerce'],
        'problems' => [
            ['title' => 'O site não transmite confiança', 'text' => 'Um site profissional antigo, lento ou confuso faz muitos potenciais clientes desistirem antes de entrar em contacto.'],
            ['title' => 'A empresa depende apenas de redes sociais', 'text' => 'As redes sociais ajudam, mas não substituem uma presença própria, pesquisável e controlada pela empresa.'],
            ['title' => 'Há visitas, mas poucos pedidos', 'text' => 'Revemos a mensagem, a hierarquia, os formulários e as chamadas para ação para reduzir fricção.'],
        ],
        'deliverables' => ['Sessão de descoberta para definir objetivos, público e páginas necessárias', 'Estrutura de conteúdos e copy orientada a pedidos de contacto', 'Web design responsivo para telemóvel, tablet e computador', 'Formulário, WhatsApp ou outro canal de contacto adequado ao negócio', 'SEO técnico de base, analytics e preparação para indexação no Google', 'Formação e plano de manutenção ou evolução após o lançamento'],
        'process' => [
            ['step' => '01 · Descoberta', 'title' => 'Definimos o que o site precisa de fazer', 'text' => 'Percebemos serviços, público, dúvidas frequentes e a ação que cada visitante deve tomar.'],
            ['step' => '02 · Estrutura e conteúdo', 'title' => 'Organizamos a mensagem antes de desenhar', 'text' => 'Criamos páginas, conteúdos e chamadas para ação que facilitam a decisão do cliente.'],
            ['step' => '03 · Design e desenvolvimento', 'title' => 'Construímos uma experiência rápida e clara', 'text' => 'Desenvolvemos, testamos em vários dispositivos e preparamos a base técnica para pesquisa.'],
            ['step' => '04 · Lançamento e evolução', 'title' => 'Publicamos, medimos e melhoramos', 'text' => 'Confirmamos contactos, medição e pontos de melhoria para o website continuar a gerar valor.'],
        ],
        'faqs' => [
            ['question' => 'O website fica preparado para aparecer no Google?', 'answer' => 'Incluímos SEO técnico de base, estrutura clara, sitemap e indexação preparada. O posicionamento para pesquisas como criação de sites no Porto depende depois da concorrência, conteúdo, autoridade e trabalho contínuo.'],
            ['question' => 'Posso atualizar o website depois do lançamento?', 'answer' => 'Sim. Definimos consigo o nível de autonomia necessário e disponibilizamos formação, manutenção ou evolução contínua conforme o projeto.'],
            ['question' => 'Um website inclui publicidade Google Ads?', 'answer' => 'O website fica preparado para campanhas e medição. A gestão de Google Ads é um serviço separado, pensado quando faz sentido acelerar a captação.'],
        ],
    ],
    'software' => [
        'slug' => 'software-a-medida',
        'seo' => [
            'title' => 'Desenvolvimento de Software à Medida | NexusVora',
            'description' => 'Desenvolvimento de software à medida para empresas: sistemas internos, plataformas web, dashboards e aplicações adaptadas à sua operação.',
        ],
        'eyebrow' => 'Sistemas personalizados',
        'title' => 'Desenvolvimento de software à medida para a forma como a sua empresa trabalha.',
        'lead' => 'Quando as folhas de cálculo, as ferramentas genéricas e os processos manuais deixam de acompanhar o negócio, um software de gestão à medida pode devolver controlo à equipa.',
        'intro' => 'Desenvolvemos software à medida, sistemas internos, plataformas web, aplicações de gestão e dashboards. Seja um backoffice, CRM, sistema de stock ou aplicação web, o objetivo é tornar a operação mais visível, organizada e fácil de evoluir.',
        'accent' => 'blue',
        'features' => [
            ['title' => 'Diagnóstico do processo', 'text' => 'Mapeamos o problema, os utilizadores e o resultado que o sistema de gestão tem de produzir antes de escrever código.'],
            ['title' => 'Aplicações que acompanham o negócio', 'text' => 'Ferramentas internas, backoffices, áreas de cliente e aplicações web com regras adaptadas à sua operação.'],
            ['title' => 'Evolução sem dependência cega', 'text' => 'Construção por fases, prioridades claras e uma base preparada para novas funcionalidades e integrações com ERP ou CRM.'],
        ],
        'for' => ['Empresas com processos que já não cabem em ferramentas genéricas', 'Equipas que precisam de centralizar informação', 'Negócios que querem transformar uma ideia numa plataforma digital'],
        'problems' => [
            ['title' => 'A operação vive em folhas de cálculo', 'text' => 'Informação dispersa, versões diferentes e tarefas manuais tornam difícil saber o que está realmente a acontecer.'],
            ['title' => 'A equipa trabalha em ferramentas que não encaixam', 'text' => 'Uma solução genérica pode obrigar a empresa a adaptar-se ao software, em vez de o software apoiar o processo real.'],
            ['title' => 'Não existe visão de gestão', 'text' => 'Criamos backoffices, dashboards e sistemas de gestão com regras de negócio que permitem acompanhar o que importa sem procurar dados em vários sítios.'],
        ],
        'deliverables' => ['Levantamento do processo atual, utilizadores e regras de negócio', 'Proposta por fases, com prioridades, âmbito e pontos de validação', 'Aplicação web, sistema interno, CRM ou plataforma adaptada ao caso de uso', 'Base de dados, permissões e fluxos adequados à equipa', 'Integrações necessárias com ERP, CRM ou ferramentas existentes', 'Documentação, formação e plano de evolução após a entrega'],
        'process' => [
            ['step' => '01 · Levantamento', 'title' => 'Mapeamos o processo que precisa de melhorar', 'text' => 'Identificamos tarefas, exceções, dados e pessoas envolvidas antes de decidir o que construir.'],
            ['step' => '02 · Desenho da solução', 'title' => 'Transformamos necessidades em fluxos claros', 'text' => 'Definimos prioridades, ecrãs, regras e integrações para reduzir risco antes do desenvolvimento.'],
            ['step' => '03 · Construção por etapas', 'title' => 'Entregamos uma parte útil de cada vez', 'text' => 'Validamos com a equipa durante o desenvolvimento e ajustamos com base na utilização real.'],
            ['step' => '04 · Adoção e evolução', 'title' => 'Apoiamos a entrada em produção', 'text' => 'Formamos utilizadores, acompanhamos a operação e planeamos a evolução que fizer sentido.'],
        ],
        'faqs' => [
            ['question' => 'Preciso de saber exatamente o software que quero?', 'answer' => 'Não. O ponto de partida pode ser um problema operacional. O diagnóstico serve precisamente para decidir se vale a pena criar software e qual a primeira versão útil.'],
            ['question' => 'Podemos desenvolver por fases?', 'answer' => 'Sim. Começamos pelas funções com mais impacto, validamos com os utilizadores e evoluímos sem tentar resolver tudo de uma vez.'],
            ['question' => 'O novo sistema pode ligar às ferramentas que já usamos?', 'answer' => 'Sempre que existirem integrações viáveis, avaliamos APIs, ERP, CRM, exportações, importações e regras de sincronização antes de propor a solução.'],
        ],
    ],
    'integrations' => [
        'slug' => 'integracoes-sistemas',
        'seo' => [
            'title' => 'Integração de Sistemas, APIs, CRM e ERP | NexusVora',
            'description' => 'Integração de sistemas, APIs, CRM e ERP para empresas. Ligamos PrestaShop, e-commerce e ferramentas internas para reduzir erros e trabalho manual.',
        ],
        'eyebrow' => 'Integrações & dados',
        'title' => 'Integração de sistemas para eliminar trabalho duplicado e erros de informação.',
        'lead' => 'A equipa não deve copiar dados entre CRM, ERP, loja online e outros sistemas, nem descobrir falhas depois de uma encomenda, pedido ou atualização importante.',
        'intro' => 'Fazemos integração de sistemas, APIs, CRM, ERP, PrestaShop, e-commerce e ferramentas internas para que a informação circule de forma fiável. O resultado é menos duplicação, menos atrasos e mais clareza sobre a operação.',
        'accent' => 'purple',
        'features' => [
            ['title' => 'Integração entre plataformas', 'text' => 'Unimos as ferramentas que a empresa já usa sem obrigar a substituir tudo de uma vez.'],
            ['title' => 'Dados sincronizados', 'text' => 'Produtos, encomendas, clientes e estados atualizados onde são necessários, entre ERP, CRM e e-commerce.'],
            ['title' => 'Integrações pensadas para durar', 'text' => 'APIs, regras, monitorização e tratamento de falhas para processos mais fiáveis.'],
        ],
        'for' => ['E-commerce com operações em várias plataformas', 'Empresas com CRM, ERP ou ferramentas que não comunicam', 'Equipas que perdem tempo em importações e exportações manuais'],
        'problems' => [
            ['title' => 'Os mesmos dados são introduzidos várias vezes', 'text' => 'Copiar clientes, produtos, stock ou encomendas entre sistemas consome tempo e cria erros que só aparecem mais tarde.'],
            ['title' => 'O ERP, CRM e a loja online não comunicam', 'text' => 'Quando cada ferramenta tem uma versão diferente da informação, a equipa perde controlo sobre vendas, stock e acompanhamento comercial.'],
            ['title' => 'Uma falha de sincronização passa despercebida', 'text' => 'Uma integração robusta precisa de regras claras, registos e alertas para que a empresa consiga agir antes de afetar o cliente.'],
        ],
        'deliverables' => ['Mapeamento de sistemas, dados, regras e pontos onde a informação deve circular', 'Desenho da integração entre ERP, CRM, e-commerce, PrestaShop ou ferramentas internas', 'Ligação por API, webhooks, importação ou exportação, conforme a capacidade de cada plataforma', 'Sincronização de produtos, stock, encomendas, clientes, documentos ou estados relevantes', 'Registo de falhas, alertas e regras para lidar com exceções', 'Documentação técnica e acompanhamento após a entrada em produção'],
        'process' => [
            ['step' => '01. Mapeamento', 'title' => 'Percebemos o que deve comunicar com o quê', 'text' => 'Identificamos sistemas, dados, responsáveis, frequência de sincronização e o impacto de cada falha.'],
            ['step' => '02. Regras de integração', 'title' => 'Definimos a fonte certa para cada dado', 'text' => 'Decidimos qual sistema cria, altera e valida cada informação para evitar duplicações e conflitos.'],
            ['step' => '03. Desenvolvimento e testes', 'title' => 'Construímos e testamos cenários reais', 'text' => 'Validamos casos normais, exceções e recuperação de falhas antes de colocar a integração em produção.'],
            ['step' => '04. Monitorização', 'title' => 'Acompanhamos o funcionamento', 'text' => 'Confirmamos os resultados, documentamos o processo e melhoramos quando a operação ou as plataformas evoluem.'],
        ],
        'faqs' => [
            ['question' => 'É possível integrar um ERP ou CRM que já usamos?', 'answer' => 'Avaliamos a API, os dados disponíveis, a documentação e alternativas como importações ou exportações. A solução depende da capacidade técnica de cada plataforma.'],
            ['question' => 'Podem integrar PrestaShop com gestão de stock e encomendas?', 'answer' => 'Sim. Avaliamos a sincronização de produtos, stock, encomendas, estados e documentos de acordo com o processo e as ferramentas usadas pela empresa.'],
            ['question' => 'O que acontece se uma integração falhar?', 'answer' => 'Definimos registos, alertas e tratamento de exceções para que uma falha seja identificada e corrigida sem depender de descoberta manual.'],
        ],
    ],
    'automation' => [
        'slug' => 'automacao-ia-empresas',
        'seo' => [
            'title' => 'Automação de Processos com IA para Empresas | NexusVora',
            'description' => 'Automação de processos com IA para empresas. Reduza tarefas repetitivas, integre ferramentas e dê mais tempo à sua equipa para tarefas importantes.',
        ],
        'eyebrow' => 'Automação & inteligência artificial',
        'title' => 'Automação de processos com IA para recuperar tempo e reduzir falhas.',
        'lead' => 'A inteligência artificial para empresas só cria valor quando resolve uma tarefa concreta, como responder melhor, processar mais depressa ou dar informação útil no momento certo.',
        'intro' => 'Identificamos tarefas repetitivas e criamos automação de processos, integrações e assistentes com IA que apoiam a operação. A equipa mantém o controlo e deixa de perder tempo em trabalho administrativo que pode ser feito automaticamente.',
        'accent' => 'gold',
        'features' => [
            ['title' => 'Automação de tarefas e fluxos', 'text' => 'Pedidos, notificações, documentos, relatórios e tarefas que passam a acontecer no momento certo.'],
            ['title' => 'IA aplicada ao contexto', 'text' => 'Assistentes, processamento de documentos e respostas inteligentes com regras, dados e validação adequados ao seu negócio.'],
            ['title' => 'Implementação com controlo', 'text' => 'Começamos por um processo prioritário, medimos o impacto e evoluímos a automação com segurança.'],
        ],
        'for' => ['Equipas sobrecarregadas com tarefas administrativas', 'Empresas que querem responder e tratar pedidos mais depressa', 'Negócios com dados dispersos e processos manuais'],
        'problems' => [
            ['title' => 'Tarefas repetitivas ocupam demasiado tempo', 'text' => 'Pedidos, documentos, emails, atualizações e relatórios consomem horas que a equipa podia dedicar a clientes e decisões.'],
            ['title' => 'Os contactos chegam, mas perdem-se', 'text' => 'Quando os pedidos entram por vários canais sem processo, a resposta atrasa e oportunidades ficam sem seguimento.'],
            ['title' => 'A IA é usada sem objetivo definido', 'text' => 'Em vez de adicionar mais uma ferramenta, começamos por um fluxo específico onde a automação pode ser medida e controlada.'],
        ],
        'deliverables' => ['Mapeamento da tarefa ou fluxo prioritário antes da implementação', 'Desenho de automação de processos, regras e pontos de validação humana', 'Integração com email, formulários, CRM, e-commerce ou outras ferramentas existentes', 'Assistentes com IA configurados para o contexto e limites definidos', 'Automatização de tarefas, registo de ações, tratamento de exceções e acompanhamento do funcionamento', 'Formação da equipa e plano para medir tempo poupado ou qualidade do processo'],
        'process' => [
            ['step' => '01 · Prioridade', 'title' => 'Escolhemos um processo concreto', 'text' => 'Começamos onde há maior repetição, atraso ou risco de erro e onde o resultado pode ser acompanhado.'],
            ['step' => '02 · Regras e validação', 'title' => 'Definimos o que automatizar e o que rever', 'text' => 'A automação não elimina decisões importantes. Criamos pontos de controlo e exceções para a equipa.'],
            ['step' => '03 · Integração e testes', 'title' => 'Ligamos as ferramentas e testamos cenários reais', 'text' => 'Validamos dados, permissões, respostas e falhas antes de colocar o fluxo em produção.'],
            ['step' => '04 · Medição e melhoria', 'title' => 'Acompanhamos o impacto', 'text' => 'Medimos tempo, qualidade, erros e utilização para decidir a próxima melhoria com base em resultados.'],
        ],
        'faqs' => [
            ['question' => 'A automação com IA substitui a equipa?', 'answer' => 'O objetivo é retirar trabalho repetitivo e dar melhores ferramentas à equipa. Decisões sensíveis e exceções podem continuar com validação humana.'],
            ['question' => 'É possível automatizar apenas uma parte do processo?', 'answer' => 'Sim. Um projeto piloto bem escolhido é normalmente a forma mais segura de validar impacto antes de expandir a automação.'],
            ['question' => 'A IA pode usar dados da empresa com segurança?', 'answer' => 'A solução de IA para empresas é desenhada de acordo com os dados necessários, acessos, retenção e regras do processo. Estes pontos são definidos antes da implementação.'],
        ],
    ],
    'ecommerce' => [
        'slug' => 'ecommerce-operacoes',
        'seo' => [
            'title' => 'E-commerce, Gestão de Stock e Encomendas | NexusVora',
            'description' => 'Soluções de e-commerce, gestão de stock e encomendas. Integrações PrestaShop e ferramentas internas para vender online com mais controlo.',
        ],
        'eyebrow' => 'E-commerce & operações',
        'title' => 'E-commerce, stock e encomendas organizados num processo que a equipa consegue controlar.',
        'lead' => 'Vender online é apenas o início. O desafio está em processar encomendas, gerir stock e manter produtos, equipa e clientes sincronizados.',
        'intro' => 'Criamos e evoluímos e-commerce e sistemas de gestão de stock e encomendas, incluindo integrações PrestaShop, processamento operacional e ferramentas internas. Juntamos desenvolvimento técnico e experiência prática de operação.',
        'accent' => 'green',
        'features' => [
            ['title' => 'Gestão de stock e encomendas', 'text' => 'Visibilidade sobre produtos, disponibilidade e tarefas de preparação de encomendas.'],
            ['title' => 'Lojas e plataformas ligadas', 'text' => 'Integrações entre PrestaShop, e-commerce, sistemas de gestão, catálogo e processos internos.'],
            ['title' => 'Operação preparada para escalar', 'text' => 'Menos exceções manuais, mais consistência e melhor acompanhamento da equipa.'],
        ],
        'for' => ['Lojas online com crescimento de encomendas', 'Retalhistas com problemas de stock ou catálogo', 'Empresas que usam PrestaShop ou precisam de integrações personalizadas'],
        'problems' => [
            ['title' => 'O stock mostrado na loja não é fiável', 'text' => 'Vender um produto indisponível ou bloquear stock sem necessidade prejudica a margem, a confiança e o trabalho da equipa.'],
            ['title' => 'As encomendas são tratadas manualmente', 'text' => 'Quando é preciso consultar vários sistemas, imprimir listas e atualizar estados à mão, cada pedido demora mais e fica mais exposto a falhas.'],
            ['title' => 'O catálogo e os canais de venda não estão alinhados', 'text' => 'Produtos, preços, atributos e disponibilidade precisam de uma gestão consistente para que a operação não dependa de correções constantes.'],
        ],
        'deliverables' => ['Diagnóstico do fluxo entre loja online, stock, encomendas, faturação e expedição', 'Desenvolvimento ou evolução de e-commerce e módulos PrestaShop', 'Sistema interno para preparação, acompanhamento ou priorização de encomendas', 'Integração de produtos, stock, clientes, encomendas e estados com as ferramentas existentes', 'Regras operacionais para reservas, exceções, alertas e tratamento de indisponibilidades', 'Dashboards, formação e apoio à evolução da operação'],
        'process' => [
            ['step' => '01. Operação atual', 'title' => 'Mapeamos o caminho de cada encomenda', 'text' => 'Percebemos como entram pedidos, como o stock é atualizado e onde existem atrasos, falhas ou tarefas duplicadas.'],
            ['step' => '02. Prioridade operacional', 'title' => 'Escolhemos o ponto com maior impacto', 'text' => 'Pode ser stock, catálogo, processamento de encomendas, integração PrestaShop ou uma ferramenta usada pela equipa.'],
            ['step' => '03. Implementação e testes', 'title' => 'Construímos sem parar a operação', 'text' => 'Validamos produtos, encomendas, regras e cenários excecionais com dados próximos da realidade.'],
            ['step' => '04. Acompanhamento', 'title' => 'Medimos e melhoramos', 'text' => 'Acompanhamos utilização, erros e tempo de operação para evoluir a solução à medida que o volume cresce.'],
        ],
        'faqs' => [
            ['question' => 'Trabalham com PrestaShop?', 'answer' => 'Sim. Podemos desenvolver módulos, integrações e ferramentas de apoio à operação de lojas PrestaShop, de acordo com a versão e o contexto técnico existente.'],
            ['question' => 'Conseguem integrar stock e encomendas com o sistema de gestão?', 'answer' => 'Avaliamos como o sistema atual expõe os dados e definimos uma sincronização adequada para produtos, stock, encomendas, estados e documentos.'],
            ['question' => 'É necessário substituir a loja online atual?', 'answer' => 'Nem sempre. Muitas melhorias podem ser feitas através de módulos, integrações ou sistemas de apoio. A decisão depende das limitações e do custo de evolução da plataforma atual.'],
        ],
    ],
    'seo' => [
        'slug' => 'seo-porto',
        'seo' => [
            'title' => 'SEO Local no Porto para Empresas | NexusVora',
            'description' => 'SEO local no Porto para empresas que querem aparecer no Google. SEO técnico, páginas de serviço, conteúdos úteis e foco em oportunidades reais.',
        ],
        'eyebrow' => 'Visibilidade orgânica',
        'title' => 'SEO local no Porto para aparecer no Google quando os seus clientes pesquisam.',
        'lead' => 'SEO não é repetir palavras-chave. É criar uma base técnica, páginas úteis e sinais de confiança para o Google apresentar a empresa às pessoas certas quando pesquisam o serviço.',
        'intro' => 'Trabalhamos SEO local no Porto através de auditoria SEO, SEO técnico, estrutura de páginas, conteúdos e medição. Começamos pelo que impede o site de aparecer no Google e definimos prioridades ligadas aos serviços que a empresa realmente vende.',
        'accent' => 'cyan',
        'features' => [
            ['title' => 'Auditoria SEO, base técnica e indexação', 'text' => 'Canonicals, sitemap, velocidade, estrutura e os sinais que ajudam o Google a interpretar o site.'],
            ['title' => 'Páginas que respondem à procura', 'text' => 'Conteúdo comercial, SEO on-page e conteúdos úteis para necessidades reais, sem duplicação artificial.'],
            ['title' => 'Medição transparente', 'text' => 'Google Search Console, impressões, páginas e leads para perceber o que está a evoluir.'],
        ],
        'for' => ['Empresas do Porto que não aparecem para os seus serviços', 'Negócios com site, mas sem tráfego orgânico qualificado', 'Empresas que querem construir visibilidade sustentável'],
        'problems' => [
            ['title' => 'O website não aparece para os serviços vendidos', 'text' => 'Sem páginas claras, títulos adequados e informação útil, o Google pode não associar a empresa às pesquisas dos potenciais clientes.'],
            ['title' => 'Existem visitas, mas não existem contactos', 'text' => 'SEO precisa de atrair a pesquisa certa e de levar a uma página que responde à intenção do visitante e facilita o pedido de contacto.'],
            ['title' => 'O investimento não é acompanhado por dados', 'text' => 'Sem Google Search Console, Analytics e objetivos de conversão, é difícil distinguir visibilidade real de métricas sem valor comercial.'],
        ],
        'deliverables' => ['Auditoria SEO técnica e de conteúdos para identificar bloqueios e oportunidades', 'Revisão de indexação, sitemap, canonicals, desempenho e estrutura do website', 'Pesquisa de palavras-chave orientada a serviços, localização e intenção comercial', 'Otimização SEO on-page de títulos, meta descrições, headings e conteúdos prioritários', 'Plano de páginas de serviço, conteúdos úteis e ligação interna', 'Medição em Google Search Console, Analytics e acompanhamento de contactos orgânicos'],
        'process' => [
            ['step' => '01. Diagnóstico SEO', 'title' => 'Descobrimos o que limita a visibilidade', 'text' => 'Analisamos indexação, conteúdo, concorrência, pesquisas relevantes e os pontos técnicos que impedem crescimento.'],
            ['step' => '02. Prioridades', 'title' => 'Ligamos as pesquisas aos serviços que vendemos', 'text' => 'Escolhemos páginas e temas com intenção comercial, começando pelas oportunidades mais realistas para o negócio.'],
            ['step' => '03. Implementação', 'title' => 'Melhoramos a base e o conteúdo', 'text' => 'Aplicamos correções técnicas, melhoramos páginas e criamos ativos úteis sem produzir conteúdo apenas para preencher o site.'],
            ['step' => '04. Medição', 'title' => 'Acompanhamos impressões, posições e contactos', 'text' => 'Revemos os dados, identificamos novas oportunidades e ajustamos o plano a partir do que as pessoas realmente pesquisam.'],
        ],
        'faqs' => [
            ['question' => 'Quanto tempo demora o SEO a dar resultados?', 'answer' => 'Depende do estado do site, concorrência e histórico do domínio. As melhorias técnicas podem ser reconhecidas mais cedo, mas crescimento consistente de tráfego e posições exige acompanhamento durante vários meses.'],
            ['question' => 'O SEO local ajuda empresas que atendem no Porto?', 'answer' => 'Sim. O SEO local ajuda a relacionar a empresa, os serviços e a área onde trabalha com pesquisas relevantes, incluindo a presença no Perfil de Empresa no Google.'],
            ['question' => 'Podem trabalhar SEO num website já existente?', 'answer' => 'Sim. Começamos por uma auditoria para decidir o que deve ser corrigido, reestruturado ou criado, sem assumir que é necessário refazer todo o site.'],
        ],
    ],
    'ads' => [
        'slug' => 'google-ads-porto',
        'seo' => [
            'title' => 'Gestão de Google Ads no Porto | NexusVora',
            'description' => 'Gestão de Google Ads no Porto para empresas. Campanhas de pesquisa, landing pages e medição de conversões com foco em contactos qualificados.',
        ],
        'eyebrow' => 'Google Ads & captação',
        'title' => 'Google Ads no Porto para transformar pesquisas em contactos comerciais.',
        'lead' => 'Quando a empresa precisa de gerar procura agora, campanhas Google Ads bem medidas ligam a oferta às pessoas que já estão a pesquisar esse serviço.',
        'intro' => 'Criamos e otimizamos campanhas Google Ads de pesquisa, landing pages e medição de conversões para empresas no Porto. As decisões são tomadas a partir de contactos e qualidade comercial, não apenas de cliques.',
        'accent' => 'blue',
        'features' => [
            ['title' => 'Campanhas de pesquisa', 'text' => 'Palavras-chave, localização, anúncios e orçamento alinhados com a oferta e margem do negócio.'],
            ['title' => 'Landing pages que convertem', 'text' => 'A campanha Google Ads precisa de uma página clara, rápida e preparada para transformar interesse em contacto.'],
            ['title' => 'Otimização por conversão', 'text' => 'Acompanhamos custos, termos de pesquisa e qualidade dos leads para decidir onde investir.'],
        ],
        'for' => ['Empresas que precisam de gerar pedidos mais depressa', 'Negócios locais no Porto com serviços de procura ativa', 'Equipas que querem parar de medir sucesso apenas por cliques'],
        'problems' => [
            ['title' => 'Há orçamento investido, mas poucos contactos', 'text' => 'Sem uma oferta clara, palavras-chave ajustadas e medição de conversões, é fácil gerar cliques que não se tornam oportunidades.'],
            ['title' => 'Os anúncios aparecem para pesquisas erradas', 'text' => 'A escolha de termos, localizações, correspondências e negativas influencia diretamente a qualidade das visitas pagas.'],
            ['title' => 'A landing page não acompanha a campanha', 'text' => 'Uma página lenta, genérica ou sem uma chamada clara pode desperdiçar o interesse criado pelo anúncio.'],
        ],
        'deliverables' => ['Diagnóstico da oferta, margem, área geográfica e objetivo comercial da campanha', 'Pesquisa de palavras-chave e estrutura de campanhas Google Ads de pesquisa', 'Criação ou melhoria de anúncios, extensões e mensagens orientadas ao contacto', 'Landing page ou melhorias na página de destino para reduzir fricção', 'Configuração de medição de chamadas, formulários e outros contactos relevantes', 'Otimização contínua de termos de pesquisa, orçamento, custo por lead e qualidade comercial'],
        'process' => [
            ['step' => '01. Oferta e objetivo', 'title' => 'Definimos o que vale a pena promover', 'text' => 'Alinhamos serviço, público, localização, margem e o contacto que representa uma oportunidade real para a empresa.'],
            ['step' => '02. Campanha e página', 'title' => 'Ligamos a pesquisa à proposta certa', 'text' => 'Construímos campanhas de pesquisa e páginas de destino que respondem diretamente ao que a pessoa procura.'],
            ['step' => '03. Medição', 'title' => 'Registamos as conversões importantes', 'text' => 'Configuramos o acompanhamento de formulários, chamadas e ações que permitem avaliar a campanha com dados.'],
            ['step' => '04. Otimização', 'title' => 'Melhoramos com base na qualidade dos contactos', 'text' => 'Revemos termos de pesquisa, custos, anúncios e páginas para concentrar o investimento no que traz oportunidades melhores.'],
        ],
        'faqs' => [
            ['question' => 'Quanto preciso de investir em Google Ads?', 'answer' => 'O orçamento depende do serviço, concorrência, área geográfica e valor de cada novo cliente. Antes de definir um valor, avaliamos se existe procura e se a campanha pode ser medida corretamente.'],
            ['question' => 'Google Ads funciona para negócios locais no Porto?', 'answer' => 'Pode funcionar muito bem quando existe procura ativa e uma oferta clara. Segmentamos as campanhas pela zona de atuação e pelas pesquisas com maior intenção comercial.'],
            ['question' => 'Como sabemos se os anúncios estão a trazer clientes?', 'answer' => 'Configuramos conversões como pedidos de contacto, chamadas ou formulários e cruzamos esses dados com a qualidade comercial dos leads recebidos.'],
        ],
    ],
    'social' => [
        'slug' => 'gestao-redes-sociais-empresas',
        'seo' => [
            'title' => 'Gestão de Redes Sociais para Empresas | NexusVora',
            'description' => 'Gestão de redes sociais para empresas: estratégia, conteúdos e acompanhamento para comunicar com consistência e transformar atenção em oportunidades.',
        ],
        'eyebrow' => 'Redes sociais & conteúdo',
        'title' => 'Gestão de redes sociais para empresas que querem comunicar com consistência.',
        'lead' => 'Publicar por publicar raramente ajuda o negócio. Uma presença social eficaz começa por saber com quem falar, que valor mostrar e que ação facilitar.',
        'intro' => 'Planeamos e gerimos conteúdos para redes sociais de empresas, alinhando estratégia, identidade visual, calendário editorial e objetivos comerciais. A comunicação mantém-se reconhecível entre canais e dá à equipa um processo claro para participar.',
        'accent' => 'purple',
        'features' => [
            ['title' => 'Estratégia editorial', 'text' => 'Definimos temas, formatos, frequência e objetivos a partir do público e da oferta da empresa.'],
            ['title' => 'Conteúdo coerente com a marca', 'text' => 'Criamos publicações e peças visuais com uma voz consistente e adaptada a cada rede.'],
            ['title' => 'Acompanhamento com propósito', 'text' => 'Analisamos alcance, interação e ações relevantes para ajustar o plano ao longo do tempo.'],
        ],
        'for' => ['Empresas sem tempo ou equipa para publicar com regularidade', 'Marcas que precisam de uma presença mais profissional', 'Negócios que querem ligar conteúdo a campanhas e contactos'],
        'problems' => [
            ['title' => 'A comunicação é irregular', 'text' => 'Publicações sem calendário tornam difícil criar reconhecimento e manter a empresa presente junto do público.'],
            ['title' => 'O conteúdo não mostra o valor da empresa', 'text' => 'Uma linha editorial clara ajuda a explicar serviços, responder a dúvidas e demonstrar experiência.'],
            ['title' => 'Há interação, mas não há próximos passos', 'text' => 'Cada canal deve ajudar o público a avançar para uma conversa, visita, marcação ou pedido de informação.'],
        ],
        'deliverables' => ['Diagnóstico da presença atual, público e objetivos de comunicação', 'Estratégia editorial com pilares de conteúdo e calendário', 'Criação de copy e peças visuais ajustadas aos canais escolhidos', 'Planeamento e publicação de conteúdos conforme o âmbito acordado', 'Orientações para responder a comentários e mensagens', 'Relatório de desempenho com recomendações para o ciclo seguinte'],
        'process' => [
            ['step' => '01 · Contexto', 'title' => 'Conhecemos a marca e o público', 'text' => 'Alinhamos posicionamento, serviços, audiência, recursos disponíveis e resultados esperados.'],
            ['step' => '02 · Plano editorial', 'title' => 'Escolhemos temas e formatos', 'text' => 'Organizamos ideias, calendário e mensagens para que cada publicação tenha uma função.'],
            ['step' => '03 · Produção e publicação', 'title' => 'Criamos conteúdo com consistência', 'text' => 'Preparamos textos e visuais e coordenamos a publicação nos canais definidos.'],
            ['step' => '04 · Aprendizagem', 'title' => 'Ajustamos com base nos sinais certos', 'text' => 'Revemos desempenho e feedback para melhorar temas, formatos e chamadas à ação.'],
        ],
        'faqs' => [
            ['question' => 'Que redes sociais devo usar?', 'answer' => 'Depende do público, do tipo de serviço e da capacidade de produzir conteúdo útil para cada canal. A estratégia começa por escolher onde a empresa consegue comunicar melhor.'],
            ['question' => 'A gestão inclui responder a mensagens?', 'answer' => 'Podemos definir orientações e responsabilidades para mensagens e comentários. O âmbito de gestão de comunidade é acordado antes de começar.'],
            ['question' => 'Como medem resultados nas redes sociais?', 'answer' => 'Acompanhamos indicadores adequados ao objetivo, como alcance relevante, interação, visitas, mensagens e contactos, sem tratar seguidores como único sinal de sucesso.'],
        ],
    ],
    'ai' => [
        'slug' => 'inteligencia-artificial-empresas',
        'seo' => [
            'title' => 'Inteligência Artificial para Empresas | NexusVora',
            'description' => 'Soluções de inteligência artificial para empresas: assistentes, pesquisa sobre documentos e automação com controlo humano e foco em tarefas reais.',
        ],
        'eyebrow' => 'Inteligência artificial aplicada',
        'title' => 'Inteligência artificial para empresas, aplicada a tarefas concretas.',
        'lead' => 'A IA só é útil quando melhora um trabalho real. Identificamos onde pode apoiar a equipa e definimos limites, dados e validações antes da implementação.',
        'intro' => 'Desenhamos soluções de inteligência artificial para empresas, desde assistentes internos e pesquisa sobre documentação até classificação e apoio ao tratamento de pedidos. A implementação considera os dados necessários, as permissões e os momentos em que uma pessoa deve rever o resultado.',
        'accent' => 'gold',
        'features' => [
            ['title' => 'Caso de uso bem definido', 'text' => 'Começamos por uma tarefa, utilizadores e resultado observável, em vez de introduzir IA sem objetivo.'],
            ['title' => 'Dados e ferramentas ligados', 'text' => 'Avaliamos documentos, sistemas e integrações necessários para dar contexto útil à solução.'],
            ['title' => 'Controlo e validação', 'text' => 'Definimos acessos, limites, registos e revisão humana para os casos que exigem confirmação.'],
        ],
        'for' => ['Equipas que procuram informação em muitos documentos', 'Empresas com pedidos repetitivos que exigem triagem', 'Negócios que querem testar IA num processo com impacto mensurável'],
        'problems' => [
            ['title' => 'A informação existe, mas é difícil encontrá-la', 'text' => 'Uma pesquisa contextual pode ajudar a equipa a localizar respostas em documentação autorizada.'],
            ['title' => 'A triagem ocupa demasiado tempo', 'text' => 'A IA pode organizar pedidos e sugerir próximos passos, mantendo validação humana onde for necessária.'],
            ['title' => 'É difícil avaliar o risco da adoção', 'text' => 'Um piloto delimitado permite rever qualidade, acesso a dados, exceções e impacto antes de alargar o uso.'],
        ],
        'deliverables' => ['Mapeamento do processo e escolha de um caso de uso prioritário', 'Avaliação das fontes de dados, acessos e requisitos de privacidade', 'Protótipo ou solução de IA ligado às ferramentas acordadas', 'Regras para respostas, encaminhamentos, exceções e revisão humana', 'Registo e avaliação de qualidade com casos de utilização representativos', 'Formação da equipa e plano de acompanhamento do piloto'],
        'process' => [
            ['step' => '01 · Oportunidade', 'title' => 'Escolhemos uma tarefa com valor claro', 'text' => 'Identificamos utilizadores, frequência, limitações e o resultado que queremos melhorar.'],
            ['step' => '02 · Dados e limites', 'title' => 'Definimos contexto e permissões', 'text' => 'Acordamos que informação pode ser usada, quem acede e que respostas precisam de validação.'],
            ['step' => '03 · Piloto', 'title' => 'Testamos com exemplos reais', 'text' => 'Medimos qualidade e tratamos erros e exceções antes de alargar a utilização.'],
            ['step' => '04 · Evolução', 'title' => 'Decidimos com evidência', 'text' => 'Comparamos resultados e esforço para decidir se a solução deve evoluir, mudar ou parar.'],
        ],
        'faqs' => [
            ['question' => 'A IA pode responder com base nos documentos da empresa?', 'answer' => 'Sim, quando os documentos e permissões são adequados. A solução deve indicar as fontes utilizadas e prever encaminhamento quando não encontra informação suficiente.'],
            ['question' => 'É necessário automatizar todo o processo?', 'answer' => 'Não. Muitas vezes o melhor primeiro passo é apoiar uma etapa, como pesquisa ou triagem, e manter decisões importantes com a equipa.'],
            ['question' => 'Como se controla a qualidade das respostas?', 'answer' => 'Definimos exemplos de avaliação, limites para respostas incertas, registos e revisão humana conforme o impacto de cada utilização.'],
        ],
    ],
    'branding' => [
        'slug' => 'branding-identidade-marca',
        'seo' => [
            'title' => 'Branding e Identidade de Marca para Empresas | NexusVora',
            'description' => 'Estratégia de marca e identidade visual para empresas. Clarifique o posicionamento, a mensagem e a presença da sua marca nos canais digitais.',
        ],
        'eyebrow' => 'Marca & identidade',
        'title' => 'Uma marca clara ajuda os clientes certos a reconhecer o valor da empresa.',
        'lead' => 'A identidade da empresa deve ser coerente com aquilo que entrega. Organizamos posicionamento e expressão visual para tornar a comunicação mais reconhecível.',
        'intro' => 'Apoiamos empresas a clarificar a sua marca, desde posicionamento e mensagens principais até identidade visual e aplicação em pontos de contacto digitais. O trabalho parte da estratégia e das necessidades reais da equipa, para que a marca seja utilizável no dia a dia.',
        'accent' => 'purple',
        'features' => [
            ['title' => 'Posicionamento compreensível', 'text' => 'Clarificamos público, diferenciação, proposta de valor e a forma como a empresa quer ser reconhecida.'],
            ['title' => 'Identidade visual coerente', 'text' => 'Definimos elementos visuais que funcionam em conjunto e podem ser aplicados nos canais da marca.'],
            ['title' => 'Aplicação prática', 'text' => 'Organizamos orientações e materiais base para a equipa comunicar com mais consistência.'],
        ],
        'for' => ['Empresas a lançar ou reposicionar a sua marca', 'Negócios cuja identidade já não acompanha a oferta', 'Equipas com comunicação visual inconsistente entre canais'],
        'problems' => [
            ['title' => 'É difícil explicar o que distingue a empresa', 'text' => 'Uma proposta de valor clara ajuda clientes e equipa a compreender para quem é a oferta e porque importa.'],
            ['title' => 'Cada canal parece pertencer a uma marca diferente', 'text' => 'Regras visuais e verbais simples dão coerência ao website, redes sociais, propostas e materiais comerciais.'],
            ['title' => 'A imagem não corresponde à qualidade do serviço', 'text' => 'Uma identidade atualizada pode alinhar a primeira impressão com a experiência que a empresa entrega.'],
        ],
        'deliverables' => ['Sessão de descoberta sobre negócio, clientes e objetivos da marca', 'Definição de posicionamento, proposta de valor e mensagens principais', 'Direção visual, sistema de identidade e aplicações acordadas', 'Orientações de utilização da marca em canais digitais', 'Materiais base para website, redes sociais ou apresentação comercial', 'Entrega organizada dos elementos finais e recomendações de continuidade'],
        'process' => [
            ['step' => '01 · Descoberta', 'title' => 'Percebemos o negócio e a perceção atual', 'text' => 'Reunimos contexto sobre clientes, concorrência, objetivos e pontos fortes da empresa.'],
            ['step' => '02 · Estratégia', 'title' => 'Clarificamos a mensagem e a direção', 'text' => 'Alinhamos posicionamento, personalidade e mensagens antes de avançar para o visual.'],
            ['step' => '03 · Identidade', 'title' => 'Criamos um sistema coerente', 'text' => 'Desenvolvemos e validamos os elementos visuais e as aplicações prioritárias.'],
            ['step' => '04 · Implementação', 'title' => 'Preparamos a marca para uso real', 'text' => 'Entregamos orientações e materiais que ajudam a equipa a manter consistência.'],
        ],
        'faqs' => [
            ['question' => 'Branding inclui apenas o logótipo?', 'answer' => 'Não. O logótipo é apenas um elemento. O trabalho pode incluir posicionamento, mensagens, sistema visual e orientações para os canais da empresa.'],
            ['question' => 'É preciso mudar toda a identidade atual?', 'answer' => 'Nem sempre. Primeiro avaliamos o que já funciona e decidimos se basta ajustar elementos ou se faz sentido uma mudança mais ampla.'],
            ['question' => 'A identidade pode ser aplicada ao website e às redes sociais?', 'answer' => 'Sim. Definimos aplicações prioritárias e podemos alinhar a identidade com o website, conteúdos sociais e outros materiais digitais.'],
        ],
    ],
];
